version: "3"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pi.hole.home.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always
    networks:
      Inner-Athena:

  pihole:
    image: pihole/pihole:latest
    container_name: Inner-DNS-Control
    hostname: Inner-DNS-Control
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '443:443/tcp'
      - '8081:80/tcp'
    volumes:
      - 'pihole_dns_data:/etc/dnsmasq.d'
      - '/var/lib/docker/volumes/pihole_dns_data/_data/pihole/:/etc/pihole/'
    environment:
      ServerIP: 10.20.0.20
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pi.hole.home.lan
      VIRTUAL_PORT: 80
    restart: always
    networks:
      Inner-Athena:
        ipv4_address: 10.20.0.20

networks:
  Inner-Athena:
    name: Inner-Athena

volumes:
  pihole_dns_data:
    external: true