version: '3.2'

services:
  portainer:
    container_name: Olympiad0
    image: portainer/portainer-ce:2.11.1
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    networks:
      Inner-Athena:
    dns:
      - 10.20.0.20
    restart: always

networks:
  Inner-Athena:
    external:
      name: Inner-Athena

volumes:
  portainer_data: