name: nexus

on:
  push:
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true
      - name: Show Dagger version
        run: dagger version
    