name: nexus

on:
  push:
    branches:
      - main

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # Install Golang and check version
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
          check-latest: true

      # Install cosign and check version
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: main
      - name: Check cosign installation
        run: cosign version

      # Use Docker to login to Dockerhub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with dagger
#      - name: Dagger
#        uses: dagger/dagger-for-github@v3
#        with:
#          install-only: true
#      - name: Show Dagger version
#        run: dagger version
#      - name: Build docker image
#        uses: dagger/dagger-for-github@v3
#        with:
#          cmds: |
#            project update
#            do build
#            do load

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/nexus0:v0.7.1-${{ github.run_id }}
          push: true

      # Sign image with cosign
      - name: Sign image
        shell: bash
        run: |
          cosign sign -a commit=${{ github.sha }} \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            --key env://COSIGN_PRIVATE_KEY \
            ${{ secrets.DOCKER_USERNAME }}/nexus0:v0.7.1-${{ github.run_id }}
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}